# Generated by Django 3.2.6 on 2023-12-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='computer_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='user_score',
            field=models.IntegerField(default=0),
        ),
    ]
